# -*- coding: utf-8 -*-
"""GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2VQft-dzQ70PXh1Sxv2KmNOzE44DHN-
"""

import string
text = {
    "sentence1": "Hello, world! This is a test.",
    "sentence2": "Time flies like an arrow; fruit flies like a banana...",
    "sentence3": "Break a leg! You're going to do great."
}

punctuations = [".", ",", "?", "!", ":", ";", "'", "\"", "(", ")", "-", "-", "_", "[", "]", "/"]
stop_words = {"a", "an", "the", "is", "are", "am", "this", "that", "to", "you", "like"}
punct_set = set(punctuations)

def clean_text(text):
  # Remove punctuation
  cleaned = ""
  i = 0
  while i < len(text):
    if text[i] not in punct_set:
      cleaned += text[i]
    i += 1

  # Remove stop words
  words = cleaned.split()
  words = [w for w in words if w.lower() not in stop_words]

  # Return cleaned sentence
  return " ".join(words)

cleaned_data = [clean_text(value) for value in text.values()]
print(cleaned_data)

from nltk.stem import PorterStemmer, WordNetLemmatizer
import nltk

nltk.download('wordnet') # Download the wordnet corpus

stemer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

word = "better"

print(f"Stemmer: {stemer.stem(word)}")
print(f"Lemmatizer: {lemmatizer.lemmatize(word, pos='a')}")

