# -*- coding: utf-8 -*-
"""สำเนาของ hugging_face_Transformer_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYl-OTKDuyo6VeiWquKV96my-cz-AmVv
"""

!pip install transformers

"""## Tokens of BERT"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "The capital of Thailand is bangkok"

inputs = tokenizer(text, return_tensors="pt")

input_ids = inputs["input_ids"][0]
print("Input IDs:", input_ids)

tokens = tokenizer.convert_ids_to_tokens(input_ids)
print("Tokens:   ", tokens)

"""##Fill-mask pipeline"""

from transformers import pipeline

unmasker = pipeline('fill-mask', model='bert-base-uncased')

sentence = "The capital of Thailand is [MASK]."

results = unmasker(sentence)

for result in results[:3]:
    print(f"Predicted word: {result['token_str']} | confidence: {result['score']:.4f}")

"""### Thai Sentiment with BERT"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import torch.nn.functional as F

model_name = "poom-sci/WangchanBERTa-finetuned-sentiment"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# text = "อาหารร้านนี้อร่อยมาก พนักงานบริการดีสุดๆ ประทับใจ"
text = "พนักงานบริการห่วยสุดๆ ไม่ประทับใจ"
inputs = tokenizer(text, return_tensors="pt")

# ส่ง input เข้าโมเดล
with torch.no_grad():
    outputs = model(**inputs)

probabilities = F.softmax(outputs.logits, dim=1)
print(probabilities)

"""## The Writer with GPT2"""

from transformers import pipeline, set_seed

generator = pipeline('text-generation', model='gpt2')

prompt = "The most popular programming language is"

output = generator(prompt,  num_return_sequences=1)

print(output[0]['generated_text'])

"""## Angry GPT"""

from transformers import pipeline, set_seed

generator = pipeline('text-generation', model='gpt2')
angry_prompt = """
Human: Hello!
Bot: What do you want? Leave me alone!

Human: Can you help me?
Bot: No! Do it yourself. I am busy.

Human: What is your name?
Bot: None of your business! Go away!

Human: Have a nice day!
Bot:"""

output = generator(
    angry_prompt,  max_new_tokens=50,  min_new_tokens=20,  temperature = 0.1, no_repeat_ngram_size=2 )

print(output[0]['generated_text'].split("Bot:")[-1])

"""## Shyny GPT"""

from transformers import pipeline, set_seed

set_seed(42)
generator = pipeline('text-generation', model='gpt2')

# สร้าง Prompt ที่สอนให้พูดตะกุกตะกัก (Stuttering & Hesitation)
shy_prompt = """
Human: Hello!
Bot: U-um... h-hello... n-nice to meet you...

Human: What is your name?
Bot: I... I don't really have a name... s-sorry...

Human: Do you like parties?
Bot: O-oh no... too many people... I... I get nervous...

Human: Can you help me with this task?
Bot:"""

# สร้างคำตอบ
output = generator(
    shy_prompt,  max_new_tokens=40, temperature=0.8)

# ตัดเอาเฉพาะคำตอบ
print(output[0]['generated_text'].split("Bot:")[-1].strip())

